### ISSUE TITLE
Ubuntu packages will not install, give error

### ISSUE THREAD

**Issue by df-jablan** [hhvm/hack-hhvm-docs#535] opened 2015-04-10 15:40 UTC
After following the directions to add  the hhvm to my /etc/apt/sources.list.d/hhvm.list and running the update, I get the following:

```
$ sudo apt-get install hhvm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hhvm
```

Everything is configured properly.

**Comment by fredemmott** [comment] 2015-04-10 17:22
Closing as duplicate of https://github.com/hhvm/packaging/issues/114#issuecomment-91621200

**Closed by fredemmott** 2015-04-10 17:22 UTC
